name: 'My Workflow'

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ nfp_2VEvVeVCwwDVZLYmdUBGpEfqxPaQpCeT87ce }}
          NETLIFY_DEPLOY_TO_PROD: true